<?php

/**
 * @file
 * Contains devel_codemirror.module.
 */

/**
 * Implements hook_menu().
 */
function devel_codemirror_menu()
{
  $routes['admin/config/development/devel/codmirror'] = [
    'title' => 'Devel Codemirror settings',
    'description' => 'Access Codemirror settings for the execute php page',
    'access arguments' => ['access devel information'],
    'menu_name' => 'devel',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['devel_codemirror_settings_form'],
  ];

  return $routes;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function devel_codemirror_form_devel_execute_form_alter(array &$form, array &$form_state)
{
  $config = variable_get('devel_codemirror_settings', []);

  $path = drupal_get_path('module', 'devel_codemirror');

  $form['#attached']['js'][] = $path . '/codemirror/lib/codemirror.js';
  $form['#attached']['js'][] = $path . '/codemirror/mode/clike/clike.js';
  $form['#attached']['js'][] = $path . '/codemirror/mode/php/php.js';
  $form['#attached']['js'][] = $path . '/js/devel_codemirror.js';
  $form['#attached']['js'][] = $path . '/devel_codemirror/devel';
  $form['#attached']['css'][] = $path . '/codemirror/lib/codemirror.css';

  if (($config['theme'] ?? 'default') !== 'default') {
    $form['#attached']['css'][] = $path . '/codemirror/theme/' . $config['theme'] . '.css';
  }

  if (!empty($config['matchBrackets'])) {
    $form['#attached']['js'][] = $path . '/codemirror/addon/edit/matchbrackets.js';
  }
  if (!empty($config['autoCloseBrackets'])) {
    $form['#attached']['js'][] = $path . '/codemirror/addon/edit/closebrackets.js';
  }
  if (!empty($config['styleActiveLine'])) {
    $form['#attached']['js'][] = $path . '/codemirror/addon/selection/active-line.js';
  }

  $form['#attached']['js'][] = [
    'data' => [
      'devel' => [
        'codemirror' => $config,
      ],
    ],
    'type' => 'setting',
  ];
}
