devel_codemirror.settings:
  type: config_object
  label: 'Devel Codemirror'
  mapping:
    autoCloseBrackets:
      type: boolean
      label: 'Auto close brackets'
    matchBrackets:
      type: boolean
      label: 'Match brackets'
    lineWrapping:
      type: boolean
      label: 'Line wrapping'
    lineNumbers:
      type: boolean
      label: 'Line number'
    styleActiveLine:
      type: boolean
      label: 'Style active line'
    theme:
      type: string
      label: 'Theme'
